### ISSUE TITLE
Add "alpha" and "cp" into struct "out"

### ISSUE THREAD

**Issue by 7xinyu** [ComputationalThermodynamics/MAGEMin_C.jl#1]
I'd like to directly output thermal expansivity (alpha) and heat capacity (cp) in struct "out", so I added alpha, alpha_M, alpha_S, alpha_F, cp, cp_M, cp_S, cp_F into struct "stb" and implemented them like rho, rho_M, rho_S, rho_F. 

I  run the test0. The error is as follows:

out         = point_wise_minimization(P,T, bulk_rock, gv, DB, sys_in);
ERROR: ArgumentError: unsafe_wrap: pointer 0x40a9a5587ab16a6e is not properly aligned to 8 bytes
Stacktrace:
 [1] #unsafe_wrap#101
   @ ./pointer.jl:89 [inlined]
 [2] unsafe_wrap
   @ ./pointer.jl:87 [inlined]
 [3] create_gmin_struct(DB::MAGEMin_C.LibMAGEMin.Database, gv::MAGEMin_C.LibMAGEMin.global_variables, time::Float64)
   @ MAGEMin_C ~/.julia/packages/MAGEMin_C/5AdRw/julia/MAGEMin_wrappers.jl:208
 [4] point_wise_minimization(P::Float64, T::Float64, bulk_rock::Vector{Float64}, gv::MAGEMin_C.LibMAGEMin.global_variables, DB::MAGEMin_C.LibMAGEMin.Database, sys_in::String)
   @ MAGEMin_C ~/.julia/packages/MAGEMin_C/5AdRw/julia/MAGEMin_wrappers.jl:101
 [5] top-level scope
   @ REPL[9]:1

The code reported the error is :

    bulk_S   = unsafe_wrap(Vector{Cdouble},stb.bulk_S, gv.len_ox)

( ~/.julia/packages/MAGEMin_C/5AdRw/julia/MAGEMin_wrappers.jl:208)

It's not the code I modified. How to solve this problem, thanks a lot.

**Comment by boriskaus** [comment]
to add to this: 

1) if you say `print_info(out)`, you will see many of the additional info you are interested in such as `Cp` are already available  per phase. If you want to have system values, you would have to multiply that with the fraction of each phase. You could add that to the Julia interface (see [here](https://github.com/ComputationalThermodynamics/MAGEMin_C.jl/blob/48ff753126c090e787bdd3d0efb9bdd588dc24e4/src/MAGEMin_wrappers.jl#L254) for the printing function). 
 
2) If you add new things to the `C` version of MAGEMin (for example a new field in the output struct), you will have to recreate the Julia wrappers (see folder `/gen`), as we need to know how long the struct is on the Julia side as well

**Comment by NicolasRiel** [comment]
Note that MAGEMin v1.2.4 is being released at the moment, a fresh install is required as the Julia wrapper has been updated.

**Comment by 7xinyu** [comment]
Thanks for your reply. 

Sorry for the so late reply. I'm busy moving house these days.

Julia is 1.8.0, and the version MAGEMin_C is 1.2.3. I've reinstalled the MAGEMin_C and everything is OK.

I'm a freshman in julia, so my initial thought is to output the system alpha and cp in struct out directly. After your tip, I read the function print_info(out) directly and learned how to get the values of each phase.
