### ISSUE TITLE
 MethodError: no method matching point_wise_minimization

### ISSUE THREAD

**Issue by eazzzon** [ComputationalThermodynamics/MAGEMin_C.jl#2]
there seems to be an error with the database, once it raises `MethodError: no method matching point_wise_minimization`, I will keep to have this errors with all my calculations. below is what i have for the klb-1 example (it ran successully during my first attampt):
![image](https://user-images.githubusercontent.com/34231327/218127251-1725c297-0cb7-4241-a436-55ea84ecb612.png)

**Comment by boriskaus** [comment]
yes, that is because `P_kbar` is defined as an integer in your example (8). If you define it instead as a Float64 with 
```julia
julia> P_kbar=8.0
```
it will work as expected
