### ISSUE TITLE
Trying to access volume of garnet generated along a PT path

### ISSUE THREAD

**Issue by bknight1** [ComputationalThermodynamics/MAGEMin_C.jl#29]
I'm trying to use MAGEMin to generate a garnet along a PT path where the bulk rock undergoes fractionation due to its formation. I'm trying to access the volume % of garnet formed in the rock, I can see this information in the MAGEMin app but I'm not sure how to access it in Julia.

A single point PT example is as follows:
```
using MAGEMin_C
db="mp"
Xoxides = ["SiO2", "Al2O3", "FeO", "MgO", "MnO", "CaO", "Na2O", "K2O", "H2O"]
X = [59.77, 16.57, 5.88, 2.62, 0.07, 2.17, 1.73, 3.53, 7.666] ### in wt %
data = Initialize_MAGEMin(db, verbose=true);
out     =  single_point_minimization(4.0, 600.0, data, X=X, Xoxides=Xoxides, sys_in="wt");
```
where in the output would I access the volume of garnet?

Cheers

**Comment by NicolasRiel** [comment]
Hi,

First, all the oxides of the database must be provided i.e. ["SiO2"; "Al2O3"; "CaO"; "MgO"; "FeO"; "Fe2O3"; "K2O"; "Na2O"; "TiO2"; "MnO"; "H2O"]; even if their values is 0.0

**This is something that won't be necessary in the future release, but is a limitation of the current one.**

Long story short everything is stored in `out.`

But here is an example on how to access the data. To access the volume of garnet you first need to retrieve the array position of garnet

The following displays the stable phases
```
julia> out.ph
7-element Vector{String}:
 "fsp"
 "bi"
 "g"
 "mu"
 "q"
 "sill"
 "H2O"
```

Then I retrieve the position of "g"
```
julia> id_g = findfirst(out.ph .== "g")
3
```

Then you can access the structure holding all the information for the solution phases (out.SS_vec[id_g]).
Note that to display all the information of the SS_vec structure you need to type `out.SS_vec[id_g].` (with the dot at the end) and then hit "TAB" key

```
 julia> out.SS_vec[id_g].
 Comp                Comp_wt             G                   V                   Vp
 Vs                  alpha               bulkMod             compVariables       compVariablesNames
 cp                  deltaG              emChemPot           emComp              emComp_wt
 emFrac              emFrac_wt           emNames             enthalpy            entropy
 f                   rho                 shearMod
```
 

Here you can see all the information about garnet. **At the moment the volume of the phase is stored as J/bar/mol** (which is 10 cm^3/mol) to cm^3/mol. This will be corrected to cm^3/mol in the next release.

Also note that in the phase list `out.ph`, the pure phases are always last and to access their information you need to shift their id by the number of solution phase out.n_SS such as:

```
julia> id_sill = findfirst(out.ph .== "sill") - out.n_SS
2

julia> out.PP_vec[id_sill].
Comp      Comp_wt   G
V         Vp        Vs
alpha     bulkMod   cp
deltaG    enthalpy  entropy
f         rho       shearMod

julia> out.PP_vec[id_sill].Comp
11-element Vector{Float64}:
 0.5
 0.5
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
```

There is documentation here: https://computationalthermodynamics.github.io/MAGEMin/julia/Run.html#access-output-structure but I will add more example on the main MAGEMin_C README to help users,

Hope this helps,

**Comment by bknight1** [comment]
Thanks for the information @NicolasRiel, that's super helpful! 

I managed to find what I was looking for in the MAGEMinApp code [here](https://github.com/ComputationalThermodynamics/MAGEMinApp.jl/blob/12224c2fc46b8f2485fc69d3f7ab47df33a1c7a2/src/PTXpaths_functions.jl#L326).

**Comment by NicolasRiel** [comment]
Ah you wanted to vol%? 
I will add this to the output to the next release too

**Comment by bknight1** [comment]
Thanks @NicolasRiel, I'll keep an eye out for the update!
